### ISSUE TITLE
List of implemented endpoints

### ISSUE THREAD

**Issue by shprink** [OpenBankingToolkit/consumer-data-right-reference-implementation#81]
Complet list: https://consumerdatastandardsaustralia.github.io/standards/

* [x] Get Accounts
* [ ] Get Bulk Balances
* [ ] Get Balances For Specific Accounts
* [x] Get Account Balance
* [ ] Get Account Detail
* [x] Get Transactions For Account
* [ ] Get Transaction Detail
* [ ] Get Direct Debits For Account
* [ ] Get Bulk Direct Debits
* [ ] Get Direct Debits For Specific Accounts
* [ ] Get Scheduled Payments for Account
* [ ] Get Scheduled Payments Bulk
* [ ] Get Scheduled Payments For Specific Accounts
* [ ] Get Payees
* [ ] Get Payee Detail
* [ ] Get Products
* [ ] Get Product Detail

every endpoint is testable in Postman under "CDR - Forgerock Mock Bank" collection:

![image](https://user-images.githubusercontent.com/1388706/75875609-4d739a00-5e14-11ea-9769-dd572567e090.png)
